backend:
  name: github
  repo: SHIFT-She-Holds-In-Fist-the-Truth/SHIFT.github.io # 严格对应你的用户名/仓库名
  branch: main # 确保你的主分支叫 main
  base_url: https://shift-auth-worker.happysleepyslime.workers.dev
  auth_endpoint: auth # 对应你 Worker 里的 url.pathname === "/auth" 逻辑

media_folder: "images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "文章 (Articles)"
    folder: "articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "文章标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "使用模板", name: "layout", widget: "hidden", default: "layout.njk"}
      - {label: "正文内容", name: "body", widget: "markdown"}